[canvas]
[canvas.bg]
color = 'white'
[canvas.pen]
color = 'black'

[edges]
shape = [
    {triangle_frame = false},
]

[inner]
shape = [
    # {leaf = {size=300, fill=false}, rep=50},
    # {leaf = {size=200, fill=false}, rep=50},

    {inner_circles = 90},
    {inner_circles = 60},
    {inner_circles = 25},

]
